### ISSUE TITLE
Cannot open game [macOS]

### ISSUE THREAD

**Issue by narze** [TanametTpk/gameOutSideGame#1]
![image](https://user-images.githubusercontent.com/248741/147312244-d9c9bd5d-ca47-4de7-aa32-b917d040f4e3.png)

(macOS Monterey, Macbook M1 Pro 2021)

**Comment by mikkipastel** [comment]
I cannot open rar file then I cannot install this game in my macbook. 😢
(macOS Big Sur, Macbook Pro 13" 2017)

**Comment by bossoq** [comment]
<img width="576" alt="Screen Shot 2564-12-24 at 11 52 22" src="https://user-images.githubusercontent.com/14037246/147317866-f697bc71-62bc-412f-935d-b0fcb738bcc4.png">

Executable Permission is missing.

Workaround: `chmod +x GameOutsideGame2_Macos.app/Contents/MacOS/GameOutSideGame`

(macOS Monterey, Macbook Pro M1 2020)

**Comment by TanametTpk** [comment]
https://stackoverflow.com/questions/50577473/unity-game-compiled-in-windows-doesn-t-open-in-mac

from this topic, I use Windows platform to build this game so it's didn't make game as executable.
I use same solution from @bossoq , And it's work.

After that, I replace .zip instead of .rar that macOS can natively uncompess it. @mikkipastel
